[workspace]
members = [
    "parser-verilator",
    "formal",
    "simulator-rust",
    "simulator-rust/simulator-rust-runtime",
]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
publish = false

[workspace.lints.clippy]
into_iter_on_ref = "allow"
match_like_matches_macro = "allow"
